### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by fmsthird** [mkhstar/suneditor-react#176] opened 2021-03-01 02:02 UTC
Go to sample   page, paste the content with image and the uncaught error appears.
  
See attached image for reference.

![image](https://user-images.githubusercontent.com/15008195/109443224-f929e700-7a74-11eb-83a0-fd6f6cad8d6d.png)

**Comment by 0xdeadfa11** [comment] 2021-03-09 10:23
Seems that the issue is related directly to the [SunEditor](https://github.com/JiHong88/SunEditor) itself and pasting images wrapped into anchor. Just try to paste [minimal content](https://jsfiddle.net/dmLqavtr/) to the demo page and check console.

**Comment by mkhstar** [comment] 2021-03-21 21:04
Hi @0xdeadfa11 
Fixed in suneditor version 2.16.1

**Closed by mkhstar** 2021-03-21 21:04 UTC
